version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres_opwr_user
      POSTGRES_PASSWORD: M7cGGNSTRqkm5XZhwSLhA6hqKg2HPB5I
      POSTGRES_DB: postgres_opwr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres_opwr_user:M7cGGNSTRqkm5XZhwSLhA6hqKg2HPB5I@dpg-cubpqul6l47c73a3nfh0-a:5432/postgres_opwr"
    volumes:
      - .:/app
    command: >
      sh -c "npx prisma migrate deploy && npm start"

volumes:
  postgres_data: