version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres_opwr_user:M7cGGNSTRqkm5XZhwSLhA6hqKg2HPB5I@dpg-cubpqul6l47c73a3nfh0-a:5432/postgres_opwr"
    volumes:
      - .:/app
    command: >
      sh -c "npx prisma migrate deploy && npm start"

volumes:
  postgres_data: